apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-svc
  template:
    metadata:
      labels:
        app: blog-svc
    spec:
      containers:
      - name: blog-svc
        image: imi56/blog-svc:latest
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: blog-svc-config
                key: DATABASE_HOST
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: blog-svc-config
                key: DATABASE_USER
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: blog-svc-config
                key: DATABASE_NAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: blog-svc-secret
                key: DATABASE_PASSWORD
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: blog-svc-secret
                key: SECRET_KEY_BASE
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
spec:
  type: NodePort
  selector:
    app: blog-svc
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-svc-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-svc-db
  template:
    metadata:
      labels:
        app: blog-svc-db
    spec:
      containers:
      - name: blog-svc-db
        image: postgres:13
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: blog-svc-db-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-svc-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: blog-svc-db-config
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc-db
spec:
  selector:
    app: blog-svc-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
